perltidy

diff --git a/ci/scripts/shipit b/ci/scripts/shipit
--- a/ci/scripts/shipit
+++ b/ci/scripts/shipit
@@ -23,4 +23,13 @@ header() {
 : "${REPO_OUT:?required}" # Resulting repo state for subsequent steps
 : "${BRANCH:?required}" # The branch name, from which to build the release
 : "${GITHUB_OWNER:?required}" # The github organization / owner of the repo
-: "${VERSION_FROM:?required}" # The path to
+: "${VERSION_FROM:?required}" # The path to the Version file
+: "${GCP_SERVICE_KEY:?required}" # The GCP service key for accessing the blobstore, written to a temporary private.yml.
+
+if [[ ! -f "${VERSION_FROM}" ]]; then
+  echo >&2 "Version file (${VERSION_FROM}) not found.  Did you misconfigure Concourse?"
+  exit 2
+fi
+VERSION=$(cat "${VERSION_FROM}")
+if [[ -z "${VERSION}" ]]; then
+  echo >&2 "Version file (${VERSION_FROM}) was empty.  Did you misconfigure Concourse?
