scsi: Fix error handling in SCSI_IOCTL_SEND_COMMAND

diff --git a/jobs/keepalived/templates/keepalived_ctl b/jobs/keepalived/templates/keepalived_ctl
--- a/jobs/keepalived/templates/keepalived_ctl
+++ b/jobs/keepalived/templates/keepalived_ctl
@@ -78,4 +78,11 @@ case $1 in
     mkdir -p $RUN_DIR $LOG_DIR
     chown -R vcap:vcap $RUN_DIR $LOG_DIR
 
-    <% if p("keepalived.in
+    <% if p("keepalived.interface") == "auto" -%>
+    interface=$(interface_for_ip <%= p("keepalived.vip") %>)
+    if [[ $? != 0 || -z ${interface} ]]; then
+        echo "Could not autodetect interface to use for <%= p("keepalived.vip") %>. Cannot continue."
+        exit 1
+    fi
+    if grep "interface auto" ${CONF_DIR}/keepalived.config.template > /dev/null; then
+        sed "s/interface auto/interface ${interface}/" ${CONF_DIR}/keepalived
