Version dump

diff --git a/jobs/haproxy/templates/drain.erb b/jobs/haproxy/templates/drain.erb
--- a/jobs/haproxy/templates/drain.erb
+++ b/jobs/haproxy/templates/drain.erb
@@ -25,4 +25,18 @@ fi
 if [[ ! -f ${pidfile} ]]; then
   echo "$(date): pidfile does not exist" >> ${logfile}
   echo 0
-  ex
+  exit 0
+fi
+
+pid="$(cat ${pidfile})"
+if ! ps -p ${pid} >/dev/null; then
+  # In case haproxy_wrapper process is stale, pid will be empty,
+  # the drain job should not fail
+  echo "$(date): There was no process for the recorded haproxy_wrapper PID (${pid})." >> ${logfile}
+  echo 0
+  exit 0
+fi
+
+haproxy_wrapper_pid=$(pgrep -P "$pid" haproxy_wrapper)
+<%- if p("ha_proxy.syslog_server") == "stdout" || p("ha_proxy.syslog_server") == "stderr" -%>
+haproxy_maste
